name: Auto label ON-CALL issues

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title ?? "";
            if (!title.startsWith("[ON-CALL]")) return;

            const matches = [...title.matchAll(/\(([^)]+)\)/g)].map(m => m[1].trim());
            if (!matches.length) return;

            const current = context.payload.issue.labels.map(l => typeof l === "string" ? l : l.name);
            const toAdd = matches.filter(l => !current.includes(l));

            if (toAdd.length) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: toAdd
              });
            }
